KNOWLEDGE_MAX_RECOMMENDATIONS = 3
KNOWLEDGE_MAX_SUMMARIES = 3
KNOWLEDGE_AUDIT_DOCUMENT_LIMIT = 4
KNOWLEDGE_AUDIT_SKILL_LIMIT = 4

KNOWLEDGE_SUMMARY_MAX_CHARS = 140
KNOWLEDGE_MISSING_ITEM_MAX_CHARS = 80
KNOWLEDGE_RECOMMENDATION_TITLE_MAX_CHARS = 60
KNOWLEDGE_RECOMMENDATION_SUMMARY_MAX_CHARS = 80
KNOWLEDGE_RECOMMENDATION_REASON_MAX_CHARS = 140
KNOWLEDGE_SOURCE_LABEL_MAX_CHARS = 60
KNOWLEDGE_SOURCE_TYPE_MAX_CHARS = 40
KNOWLEDGE_SOURCE_MAX_CHARS = 80
KNOWLEDGE_SUGGESTED_TOPIC_MAX_CHARS = 120
KNOWLEDGE_EVIDENCE_EXCERPT_MAX_CHARS = 80
