ASSOCIATE_MAX_TOKENS = 8192
ASSOCIATE_MAX_HISTORY_MESSAGES = 50

PROJECT_CONTEXT_BRIEFING_MAX_TOKENS = 8192
WORK_LEARNINGS_RESULT_BUDGET = 3500
WORK_LEARNINGS_EXISTING_BUDGET = 1200

KNOWLEDGE_AUDIT_PROMPT_BUDGET = 12_000
KNOWLEDGE_AUDIT_MAX_TOKENS = 8192
KNOWLEDGE_AUDIT_SKILL_CHARS = 500
KNOWLEDGE_AGENT_SECTION_LIMIT = 520
KNOWLEDGE_PROJECT_CONTEXT_SECTION_LIMIT = 1400
KNOWLEDGE_DOCUMENTS_SECTION_LIMIT = 820
KNOWLEDGE_SKILLS_SECTION_LIMIT = 2200

TEAM_RECOMMENDATION_MAX_TOKENS = 8192

ORCHESTRATOR_MEMORY_TEAM_KNOWLEDGE_BUDGET = 800
ORCHESTRATOR_MEMORY_EPISODES_BUDGET = 600
EPISODES_MAX_ENTRIES = 10

ORCHESTRATOR_MEMORY_CTX_BUDGET = 3000
ORCHESTRATOR_MEMORY_RESEARCH_BUDGET = 3500
ORCHESTRATOR_MEMORY_WORK_LEARNINGS_BUDGET = 1200
ORCHESTRATOR_MEMORY_SKILLS_BUDGET = 3000
ORCHESTRATOR_TASK_CONTEXT_DOCS_BUDGET = 3000
ORCHESTRATOR_TASK_CONTEXT_PROJECT_BUDGET = 1800
ORCHESTRATOR_DEPENDENCY_RESULT_BUDGET = 6000
# Smart summarization: if a dependency result exceeds THRESHOLD chars, Claude summarizes
# it to TARGET_CHARS instead of brute-truncating.
ORCHESTRATOR_DEPENDENCY_SUMMARY_THRESHOLD = 3_000
ORCHESTRATOR_DEPENDENCY_SUMMARY_TARGET_CHARS = 5_000
ORCHESTRATOR_DEPENDENCY_SUMMARY_MAX_TOKENS = 2_048
CORE_SKILLS_CONSOLIDATION_THRESHOLD = 3
CORE_SKILLS_CONSOLIDATION_MAX_TOKENS = 4096

SMART_SKILLS_SELECT_MAX_TOKENS = 2048
SMART_SKILLS_SELECT_THRESHOLD = 4000

VECTOR_RETRIEVAL_TOP_K = 5

REFLECTION_TRIGGER_THRESHOLD = 5
REFLECTION_MAX_TOKENS = 4096

ORCHESTRATOR_PLANNER_MAX_TOKENS = 8192
ORCHESTRATOR_PLANNER_REPAIR_MAX_TOKENS = 4096
ORCHESTRATOR_RESULT_METADATA_MAX_TOKENS = 8192
ORCHESTRATOR_RESULT_METADATA_REPAIR_MAX_TOKENS = 4096
