ASSOCIATE_MAX_TOKENS = 8192
ASSOCIATE_MAX_HISTORY_MESSAGES = 50

PROJECT_CONTEXT_BRIEFING_MAX_TOKENS = 8192
WORK_LEARNINGS_RESULT_BUDGET = 3500
WORK_LEARNINGS_EXISTING_BUDGET = 1200

KNOWLEDGE_AUDIT_PROMPT_BUDGET = 12_000
KNOWLEDGE_AUDIT_MAX_TOKENS = 8192
KNOWLEDGE_AUDIT_SKILL_CHARS = 500
KNOWLEDGE_AGENT_SECTION_LIMIT = 520
KNOWLEDGE_PROJECT_CONTEXT_SECTION_LIMIT = 1400
KNOWLEDGE_DOCUMENTS_SECTION_LIMIT = 820
KNOWLEDGE_SKILLS_SECTION_LIMIT = 2200

TEAM_RECOMMENDATION_MAX_TOKENS = 8192

ORCHESTRATOR_MEMORY_CTX_BUDGET = 1500
ORCHESTRATOR_MEMORY_RESEARCH_BUDGET = 3500
ORCHESTRATOR_MEMORY_WORK_LEARNINGS_BUDGET = 1200
ORCHESTRATOR_MEMORY_SKILLS_BUDGET = 1500
ORCHESTRATOR_TASK_CONTEXT_DOCS_BUDGET = 3000
ORCHESTRATOR_TASK_CONTEXT_PROJECT_BUDGET = 1800
ORCHESTRATOR_DEPENDENCY_RESULT_BUDGET = 2500
ORCHESTRATOR_PLANNER_MAX_TOKENS = 8192
ORCHESTRATOR_PLANNER_REPAIR_MAX_TOKENS = 4096
ORCHESTRATOR_RESULT_METADATA_MAX_TOKENS = 8192
ORCHESTRATOR_RESULT_METADATA_REPAIR_MAX_TOKENS = 4096
