GIT_PULL_TIMEOUT_SECONDS = 120
GIT_CLONE_TIMEOUT_SECONDS = 300
GIT_PUSH_TIMEOUT_SECONDS = 180
GIT_PROVIDER_API_TIMEOUT_SECONDS = 30
GIT_PROVIDER_RESULT_MAX_CHARS = 20_000
WORKSPACE_SHELL_TIMEOUT_SECONDS = 120
MCP_CONNECTION_TEST_TIMEOUT_SECONDS = 20
MCP_TOOL_CALL_TIMEOUT_SECONDS = 45
MCP_TOOL_RESULT_MAX_CHARS = 20_000

SKILL_NOTE_MAX_CHARS = 6000
SKILL_NOTE_CONSOLIDATE_AT = 5000
SKILL_NOTE_ENTRY_MAX_CHARS = 400

SKILL_CONSOLIDATION_MAX_TOKENS = 1500
SKILL_CONSOLIDATION_INPUT_CHARS = 8000
SKILL_CONSOLIDATION_TARGET_CHARS = 4000
